[project]
name = "worm-cyoa-v6-fork"
version = "1.0.0"
description = ""
authors = [{ name = "Laureline David", email = "ltouroumov@gmail.com" }]

requires-python = "^3.11"
dependencies = [
  "rich",
  "pillow",
  "humanize",
  "lenses",
  "requests",
  "asciidag",
  "jinja2",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
